export const ON_CHANGE_GAME = 'ON_CHANGE_GAME';
export const ON_MOVE_WOLF = 'ON_MOVE_WOLF';
export const ON_MOVE_THOMAS = 'ON_MOVE_THOMAS';
export const ON_CHANGE_CREATE_GAME_DIMENSION = 'ON_CHANGE_CREATE_GAME_DIMENSION';
export const ON_CHANGE_MODE = 'ON_CHANGE_MODE';
export const ON_COLUMN_CLICKED = 'ON_COLUMN_CLICKED'; // create mode action
export const ON_UPDATE_PUZZLE_LAYOUT = 'ON_UPDATE_PUZZLE_LAYOUT'; // create mode action
export const ON_UNSELECT_COLUMNS = 'ON_UNSELECT_COLUMNS'; // create mode action
export const ON_SET_THOMAS_WOLF = 'ON_SET_THOMAS_WOLF'; // create mode action
export const ON_UNSET_THOMAS_WOLF = 'ON_UNSET_THOMAS_WOLF'; // create mode action