export const ON_CHANGE_GAME = 'ON_CHANGE_GAME';
export const ON_MOVE_WOLF = 'ON_MOVE_WOLF';
export const ON_MOVE_THOMAS = 'ON_MOVE_THOMAS';
export const ON_CHANGE_CREATE_GAME_DIMENSION = 'ON_CHANGE_CREATE_GAME_DIMENSION';